### PR TITLE
Added ViewEncapsulation.None for easier styling

### PR DESCRIPTION
**Pull request by aasukisuki**
Added ViewEncapsulation.None and .jaspero__confirmation class to the component to allow for easier customization of the default styles.

### CODE REVIEW

**Comment by aasukisuki** [comment]
Resolved code style conflicts on imports, and grabbed the updated code blocks with the formatting changes.

**Comment by ValentinFunk** [comment]
This is really nice! Any way to get it merged?

**Comment by flauc** [comment]
Hi @aasukisuki and @bytelabsco 

Thank you for all your hard work, this PR is great, however, I had too many conflicts to resolve and found it easier to just add the ViewEncapsulation.

**Comment by bytelabsco** [comment]
Awesome.  Thanks for adding the change.

**Pull request closed without merging**
